/***************************************************************************
* Copyright (c) 2013 VMware, Inc. All Rights Reserved.
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
***************************************************************************/
package com.vmware.vhadoop.api.vhm.strategy;

import com.vmware.vhadoop.api.vhm.events.ClusterScaleCompletionEvent;

/**
 * Component that is informed of ClusterScaleCompletionEvents when @ScaleStrategy instances complete processing
 * The component is a @VMChooser to allow the state stored by the @ClusterScaleCompletionListener to inform the choosing of VMs
 */
public interface ClusterScaleCompletionEventListener extends VMChooser {

   /**
    * Every ClusterScaleCompletionEvent generated by a @ScaleStrategy gets passed to this method
    * The method should not modify the event
    * 
    * @param event A @ClusterScaleCompletionEvent indicating the completion of a @ScaleStrategy for a cluster
    */
   public void registerNewEvent(final ClusterScaleCompletionEvent event);
   
}
